### PR TITLE
Created new basic symfony structure

### PR DESCRIPTION
**Pull request by dennisdegreef**
Setup symfony framework after discussion in #1

### CODE REVIEW

**Comment by fvdb** [comment]
Some of the stuff in the PR now should be ignored.

You would want to adopt this gitignore: https://github.com/symfony/symfony-standard/blob/2.7/.gitignore

**Comment by fvdb** [comment]
Also you might want to remove all the demo stuff. This means getting rid of everything in `src/Acme/`, and removing the bundle from AppKernel. Also adjust the routing config (has demo stuff as well).

**Comment by dennisdegreef** [comment]
Yes, sounds like a plan. I'll be on it somewhere today i think :) thanks.

**Comment by dennisdegreef** [comment]
This should do the trick :)

**Comment by fvdb** [comment]
Nice!

**Comment by dennisdegreef** [comment]
Awesome! :)

**Pull request merged**
